### ISSUE TITLE
Fix ZipDeploy using PackageUri

### ISSUE THREAD

**Issue by balag0** [Azure-App-Service/KuduLite#117]
When using ZipDeploy with external url requests are failing with 400 errors.

**Comment by Hazhzeng** [comment]
Hi @sanchitmehta,

Seems like this issue is now impacting quite a few customers using the ARM template "ZipDeploy" extensions in Linux skus (Consumption, App Service Plan, Premium). Please let me know if you have time to take a look.

ICM: https://portal.microsofticm.com/imp/v3/incidents/details/217607842/home

**Comment by sanchitmehta** [comment]
Fixed with PR: #186 186
